
package seriestv.interfaz;

import seriestv.objetos.SerieTV;
import java.util.Date;
import seriestv.logica.LogicaNegocio;

/**
 *
 * @author jgm
 */

//JDialog con formulario para añadir una nueva serie a la lista
//JPanel implementado Resizable para adaptar tamaño tabla a la ventana
//Menu bar que contiene menu item para agregar una nueva y otro para descubrir

public class AgregarSerieTV extends javax.swing.JDialog {
    
    private SeriesTV seriesTV;
    /**
     * Creates new form AgregarSerieTV
     */
    public AgregarSerieTV(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        seriesTV = (SeriesTV)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAgregarSerie = new javax.swing.JPanel();
        jLblNombreSerie = new javax.swing.JLabel();
        jLblNumTemp = new javax.swing.JLabel();
        jTxtFldNombreSerie = new javax.swing.JTextField();
        jLblFecEstreno = new javax.swing.JLabel();
        jSpinnerFecEstreno = new javax.swing.JSpinner();
        jCmbBoxNumTemp = new javax.swing.JComboBox<>();
        jBtnAgregar = new javax.swing.JButton();
        jLblSinopsis = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTxtAreaSinopsis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblNombreSerie.setText("Nombre SerieTV:");

        jLblNumTemp.setText("Numero Temporadas:");

        jLblFecEstreno.setText("Fecha Estreno:");

        jSpinnerFecEstreno.setModel(new javax.swing.SpinnerDateModel());

        jCmbBoxNumTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jLblSinopsis.setText("Sinopsis:");

        jTxtAreaSinopsis.setColumns(20);
        jTxtAreaSinopsis.setLineWrap(true);
        jTxtAreaSinopsis.setRows(5);
        jScrollPane.setViewportView(jTxtAreaSinopsis);

        javax.swing.GroupLayout jPanelAgregarSerieLayout = new javax.swing.GroupLayout(jPanelAgregarSerie);
        jPanelAgregarSerie.setLayout(jPanelAgregarSerieLayout);
        jPanelAgregarSerieLayout.setHorizontalGroup(
            jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarSerieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAgregarSerieLayout.createSequentialGroup()
                        .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblSinopsis)
                            .addComponent(jLblNombreSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblNumTemp)
                            .addComponent(jLblFecEstreno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerFecEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFldNombreSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBoxNumTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAgregarSerieLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCmbBoxNumTemp, jScrollPane, jSpinnerFecEstreno, jTxtFldNombreSerie});

        jPanelAgregarSerieLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLblFecEstreno, jLblNombreSerie, jLblNumTemp, jLblSinopsis});

        jPanelAgregarSerieLayout.setVerticalGroup(
            jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgregarSerieLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombreSerie)
                    .addComponent(jTxtFldNombreSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSinopsis))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbBoxNumTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNumTemp))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelAgregarSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerFecEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFecEstreno))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBtnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAgregarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAgregarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Boton para agregar los datos de una serie a la lista
    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        String nombreSerie = jTxtFldNombreSerie.getText();
        String sinopsis = jTxtAreaSinopsis.getText();
        String numTemporadas = (String)jCmbBoxNumTemp.getSelectedItem();
        Date fechaEstreno = (Date)jSpinnerFecEstreno.getValue();
        
        SerieTV serie = new SerieTV(nombreSerie, sinopsis, numTemporadas, fechaEstreno);
        
        //Se añade la serie utilizando la logica de negocio definida
        LogicaNegocio.agregarSerie(serie);
        dispose();
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JComboBox<String> jCmbBoxNumTemp;
    private javax.swing.JLabel jLblFecEstreno;
    private javax.swing.JLabel jLblNombreSerie;
    private javax.swing.JLabel jLblNumTemp;
    private javax.swing.JLabel jLblSinopsis;
    private javax.swing.JPanel jPanelAgregarSerie;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSpinner jSpinnerFecEstreno;
    private javax.swing.JTextArea jTxtAreaSinopsis;
    private javax.swing.JTextField jTxtFldNombreSerie;
    // End of variables declaration//GEN-END:variables
}
