package seriestv.interfaz;

/**
 *
 * @author JGM
 */

//Clase que permite descubrir series nuevas

public class Descubrir extends javax.swing.JDialog {
    
    private SeriesTV seriesTV;
    /**
     * Creates new form Descubrir
     */
    public Descubrir(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        seriesTV = (SeriesTV)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDescubrir = new javax.swing.JPanel();
        jLblDescubrir1 = new javax.swing.JLabel();
        jLblDescubrir3 = new javax.swing.JLabel();
        jLblDescubrir2 = new javax.swing.JLabel();
        jLblDescubrir4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelDescubrir.setLayout(new java.awt.GridLayout(2, 2));

        jLblDescubrir1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblDescubrir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seriestv/interfaz/imagenes/juegocalamar.jpg"))); // NOI18N
        jLblDescubrir1.setText(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir1.text")); // NOI18N
        jPanelDescubrir.add(jLblDescubrir1);
        jLblDescubrir1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir1.AccessibleContext.accessibleName")); // NOI18N

        jLblDescubrir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seriestv/interfaz/imagenes/thewitcher.jpg"))); // NOI18N
        jLblDescubrir3.setText(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir3.text")); // NOI18N
        jPanelDescubrir.add(jLblDescubrir3);
        jLblDescubrir3.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir3.AccessibleContext.accessibleName")); // NOI18N

        jLblDescubrir2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblDescubrir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seriestv/interfaz/imagenes/mrrobot.jpg"))); // NOI18N
        jLblDescubrir2.setText(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir2.text")); // NOI18N
        jPanelDescubrir.add(jLblDescubrir2);
        jLblDescubrir2.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir2.AccessibleContext.accessibleName")); // NOI18N

        jLblDescubrir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seriestv/interfaz/imagenes/hauntinghill.jpg"))); // NOI18N
        jLblDescubrir4.setText(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir4.text")); // NOI18N
        jPanelDescubrir.add(jLblDescubrir4);
        jLblDescubrir4.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(Descubrir.class, "Descubrir.jLblDescubrir4.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDescubrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDescubrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblDescubrir1;
    private javax.swing.JLabel jLblDescubrir2;
    private javax.swing.JLabel jLblDescubrir3;
    private javax.swing.JLabel jLblDescubrir4;
    private javax.swing.JPanel jPanelDescubrir;
    // End of variables declaration//GEN-END:variables
}
