
package seriestv.interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author jgm
 */

//JDialog con formulario para registrar un nuevo usuario

public class RegistrarUsuario extends javax.swing.JDialog {
    
    private PantallaPrincipal pantallaPrincipal;
    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal)parent;
        initComponents();
        
        //MiActionListener creado que recoge y muestra evento con la confirmacion de usuario registrado
        jBtnCrearUsuario.addActionListener(new seriestv.eventos.MiActionListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistrar = new javax.swing.JPanel();
        jLblNombre = new javax.swing.JLabel();
        jLblPasswd = new javax.swing.JLabel();
        jTxtFldNombre = new javax.swing.JTextField();
        jPsswdFld = new javax.swing.JPasswordField();
        jBtnCrearUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblNombre.setText("Nombre:");

        jLblPasswd.setText("Contraseña:");

        jTxtFldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldNombreActionPerformed(evt);
            }
        });

        jBtnCrearUsuario.setText("Crear usuario");
        jBtnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarLayout = new javax.swing.GroupLayout(jPanelRegistrar);
        jPanelRegistrar.setLayout(jPanelRegistrarLayout);
        jPanelRegistrarLayout.setHorizontalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnCrearUsuario)
                    .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblPasswd)
                            .addComponent(jLblNombre))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPsswdFld, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelRegistrarLayout.setVerticalGroup(
            jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPasswd)
                    .addComponent(jPsswdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBtnCrearUsuario)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Validacion manual sin utilzar libreria que comprueba que los campos no sean vacios
    private boolean validarRegistroUsuario(){
        String nombre = jTxtFldNombre.getText();
        String password = jPsswdFld.getText();
        
        if(nombre == null || "".equals(nombre) || password == null || "".equals(password)){
            JOptionPane.showMessageDialog(this, "El campo Nombre y Contraseña no pueden estar vacios.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    //Comportamiento boton crear usuario solicitando confirmacion para confirmar la accion
    private void jBtnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearUsuarioActionPerformed
        String nombre = jTxtFldNombre.getText();
        int crearUsuario = JOptionPane.showConfirmDialog(this, "¿Quieres crear el usuario con los datos introducidos?", "AVISO", JOptionPane.YES_NO_OPTION);
        
        if (crearUsuario == JOptionPane.YES_OPTION){
            if(validarRegistroUsuario()){
                JOptionPane.showMessageDialog(this, "Se ha registrado el usuario correctamente.", "Registro", JOptionPane.INFORMATION_MESSAGE);
            }
        }else if (crearUsuario == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "No se ha creado el usuario.", "Registro", JOptionPane.INFORMATION_MESSAGE);
        }
        
        pantallaPrincipal.mostrarNombreUsuario(nombre);
        setVisible(false);
    }//GEN-LAST:event_jBtnCrearUsuarioActionPerformed
    
    private void jTxtFldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldNombreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCrearUsuario;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblPasswd;
    private javax.swing.JPanel jPanelRegistrar;
    private javax.swing.JPasswordField jPsswdFld;
    private javax.swing.JTextField jTxtFldNombre;
    // End of variables declaration//GEN-END:variables
}
