
package seriestv.interfaz;

import java.util.List;
import seriestv.objetos.SerieTV;
import javax.swing.table.DefaultTableModel;
import seriestv.logica.LogicaNegocio;

/**
 *
 * @author jgm
 */

//JDialog que muestra la lista de series en seguimiento y barra de menu para añadir una serie nueva

public class SeriesTV extends javax.swing.JDialog {

    /**
     * Creates new form SeriesTV
     */
    public SeriesTV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refrescarTablaSeries();
    }
    
    //Aplica formato a la tabla que contiene listado de series recogiendo el lista de series
    //con el metodo get de la clase LogicaNegocio
    private void refrescarTablaSeries(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Serie", "Sinopsis", "Temporadas", "Fecha Estreno"});
        
        List<SerieTV> listaSeries = LogicaNegocio.getListaSeries();
        for(SerieTV serie : listaSeries){
            //Metodo toArrayString de la clase SerieTV con el formato de datos establecido (Date)
            dtm.addRow(serie.toArrayString());
        }
        
        jTableSeries.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneSeries = new javax.swing.JScrollPane();
        jTableSeries = new javax.swing.JTable();
        jMenuBarSeries = new javax.swing.JMenuBar();
        jMenuSerie = new javax.swing.JMenu();
        jMenuItemAñadirSerie = new javax.swing.JMenuItem();
        jMenuItemDescubrir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTableSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSeries.setViewportView(jTableSeries);

        getContentPane().add(jScrollPaneSeries);

        jMenuSerie.setText("SeriesTV");

        jMenuItemAñadirSerie.setText("Añadir SerieTV...");
        jMenuItemAñadirSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirSerieActionPerformed(evt);
            }
        });
        jMenuSerie.add(jMenuItemAñadirSerie);

        jMenuItemDescubrir.setText("Descubrir...");
        jMenuItemDescubrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDescubrirActionPerformed(evt);
            }
        });
        jMenuSerie.add(jMenuItemDescubrir);

        jMenuBarSeries.add(jMenuSerie);

        setJMenuBar(jMenuBarSeries);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Menu item que enlaza con el dialogo AgregarSerieTV
    private void jMenuItemAñadirSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirSerieActionPerformed
        AgregarSerieTV agregarSerieTV = new AgregarSerieTV(this, true);
        agregarSerieTV.setVisible(true);
        refrescarTablaSeries();
    }//GEN-LAST:event_jMenuItemAñadirSerieActionPerformed

    private void jMenuItemDescubrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescubrirActionPerformed
        Descubrir descubrir = new Descubrir(this, true);
        descubrir.setVisible(true);
    }//GEN-LAST:event_jMenuItemDescubrirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarSeries;
    private javax.swing.JMenuItem jMenuItemAñadirSerie;
    private javax.swing.JMenuItem jMenuItemDescubrir;
    private javax.swing.JMenu jMenuSerie;
    private javax.swing.JScrollPane jScrollPaneSeries;
    private javax.swing.JTable jTableSeries;
    // End of variables declaration//GEN-END:variables
}
